Display the help text if no arguments are present
The default behavior is to show all the required options regardless of
their incompatibility:
```
error: the following required arguments were not provided:
  --shared-dir <SHARED_DIR>
  --socket <SOCKET>
  --socket-path <SOCKET_PATH>
  --fd <FD>

Usage: virtiofsd --shared-dir <SHARED_DIR> --socket <SOCKET>
                 --socket-path <SOCKET_PATH> --fd <FD>

For more information, try '--help'.
```
It even shows hidden options (i.e. hide = true).

So, let's overwrite the usage help text with the "common" required
options, and display the help message if no argument are present.

Signed-off-by: German Maglione <gmaglione@redhat.com>